name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating your first issue on our project! We will get back to you as soon as we can."
        pr-message: "Thank you for your contribution through this pull request! We appreciate your work and will review it as soon as possible."
